### ISSUE TITLE
config files

### ISSUE THREAD

**Issue by daler** [NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3#8]
Starting a discussion on what should go into config files. Some caveats: this is tightly coupled to pipeline design, and will probably evolve. But I wanted to at least get something started.

I prefer YAML over JSON because it doesn't need everything in double quotes, you can add comments in the file, and it's a superset of json making serialization to json trivial if we need it.
### Example config

Here's a section of a hypothetical file, `config.yaml`, that defines what features to use. Description below. Note that this file will likely contain a lot of other config items; this is just the part dealing with features for now.

``` yaml
features_to_use = ["go_mf", "cpdb"]

features:
  cpdb:
    script: "tools/process_cpdb.py"
    inputs: "/data/datasets/rnaseq_counts.csv"
    output: "/data/datasets/cpdb_features.csv"
    prelude: "source activate test-env; python "

  go_bp:
    script: "tools/process_go.R"
    inputs:
      - "/data/datasets/downloaded/go.txt"
      - "/data/datasets/rnaseq_counts.csv"
    output: "/data/datasets/go_features.tab"
    prelude: "module load R; Rscript "
    extra: '--ontology="BP"'

  go_mf:
    script: "tools/process_go.R"
    inputs:
      - "/data/datasets/downloaded/go.txt"
      - "/data/datasets/rnaseq_counts.csv"
    output: "/data/datasets/go_features.tab"
    prelude: "module load R; Rscript "
    extra: '--ontology="MF"'
```

The idea here is to define sets of features that are prepared by providing a script, some inputs, and a single output file.  Many feature sets can be defined, and the `features_to_use` list selects which will be used.

As long as we require each script to accept command line arguments and to create a single output file (a not-unreasonable requirement), then from within the Snakefile we can automatically do the following for each selected feature set:

``` bash
{prelude} {script} {extra} {inputs} {output} && \
ln -sf {output} preprocessed_features/{name}.dat
```

For example, if the "go_mf" features are selected, the following shell command would be run by Snakemake:

``` bash
module load R; Rscript tools/process_go.R \
   --ontology=MF \
   /data/datasets/downloaded/go.txt \
   /data/datasets/rnaseq_counts.csv \
   /data/datasets/go_features.tab \
&& ln -sf /data/datasets/go_features.tab preprocessed_features/go_mf.dat
```
### Example Snakefile

The reason for the symlink at the end is 1) to make writing the dependencies in the Snakefile more straightforward and 2) to simplify organization so that all feature sets are in one place for downstream processing.

The point is that by making some reasonable requirements about the arguments a script accepts, _any arbitrary feature set we add_ to the config file will be handled by snakemake. That means checking if the input is newer than output, whether or not the output exists, and handling any downstream dependencies that would need to be re-run if one of these feature sets changes.

I haven't tested it, but something like this should work:

``` python

# read the config and tell snakemake what output files we want
config = yaml.load(open('config.yaml'))
targets = ['preprocessed_features/{0}.dat'.format(i) for i in config['features_to_run']]

rule all:
    input: targets

def _inputs(wildcards):
    """Given wildcards object from rule, return configured input files"""
    return config['features'][wildcards.name]['inputs']

# the magic happens here
rule preprocess_data:
    input: _inputs
    output: 'preprocessed_features/{name}.dat'
    run:
        # get the feature config
        fc = config['features'][wildcards.name]
        shell("""
        {fc.prelude} \
        {fc.script} \
        {fc.extra} \
        {fc.inputs} \
        {fc.output} \
        && ln -sf {fc.output} {output}
        """)
```

This means that the config file becomes the one-stop-shop for which scripts are run on which input to create which output. Making changes to the config file gets automatically propagated to the Snakefile which will run new jobs as needed.
